apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metaflow
resources:
  - namespace.yaml
  - host-bridge.yaml
  - secret.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
