apiVersion: v1
kind: Service
metadata:
  name: metaflow-service
  namespace: metaflow
  labels:
    app.kubernetes.io/name: metaflow-service
    app.kubernetes.io/part-of: signals-platform
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: metaflow-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30180
      protocol: TCP
    - name: migration
      port: 8082
      targetPort: migration
      protocol: TCP
      # no fixed nodePort for migration
