#!/usr/bin/env bash
# M2: Platform Airflow 3.x on local RKE2 (LocalExecutor + host PG + YK labels).
# Chart source: components/airflow/chart (submodule). Values: config/k8s/airflow/.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

MANIFEST_DIR="$ROOT/config/k8s/airflow"
CHART_DIR="$ROOT/components/airflow/chart"
VALUES="$MANIFEST_DIR/values-signals.yaml"
SECRET_FILE="${AIRFLOW_SECRETS_FILE:-$ROOT/build/config/airflow-secrets.env}"
RELEASE="${AIRFLOW_HELM_RELEASE:-airflow}"
NAMESPACE="${AIRFLOW_NAMESPACE:-airflow}"

# devenv may set PGHOST to a unix socket dir — force TCP for CREATE DATABASE
PGHOST="${SIGNALS_PG_HOST:-${PGHOST:-127.0.0.1}}"
if [[ "$PGHOST" == /* ]]; then
  PGHOST="127.0.0.1"
fi
PGPORT="${PGPORT:-5455}"
PGUSER="${PGUSER:-signals}"
PGSUPER="${AIRFLOW_PG_SUPERUSER:-$USER}"
AF_DB_USER="${AIRFLOW_DB_USER:-airflow}"
AF_DB_PASS="${AIRFLOW_DB_PASSWORD:-airflow}"
AF_DB_NAME="${AIRFLOW_DB_NAME:-airflow}"
NODE_IP="${SIGNALS_NODE_IP:-}"
API_URL="${AIRFLOW_API_URL:-http://127.0.0.1:30800}"
TIMEOUT="${AIRFLOW_BOOTSTRAP_TIMEOUT:-600}"

pick_kubeconfig() {
  local c
  for c in \
    "${KUBECONFIG:-}" \
    "${HOME}/.kube/rke2.yaml" \
    "${HOME}/.kube/config" \
    /etc/rancher/rke2/rke2.yaml; do
    [[ -n "$c" && -r "$c" ]] || continue
    export KUBECONFIG="$c"
    return 0
  done
  export KUBECONFIG="${HOME}/.kube/rke2.yaml"
  return 1
}

info() { echo "airflow-platform: $*"; }
die() { echo "ERROR: airflow-platform: $*" >&2; exit 1; }

k() { kubectl --kubeconfig "$KUBECONFIG" "$@"; }

pick_kubeconfig || true
info "KUBECONFIG=$KUBECONFIG"

command -v kubectl >/dev/null || die "kubectl not found"
command -v helm >/dev/null || die "helm not found"
k get ns >/dev/null 2>&1 || die "cannot reach cluster"
[[ -d "$CHART_DIR" ]] || die "chart missing at $CHART_DIR — init submodule components/airflow"
[[ -f "$VALUES" ]] || die "values missing: $VALUES"

if [[ -z "$NODE_IP" ]]; then
  NODE_IP="$(k get nodes -o jsonpath='{range .items[0].status.addresses[?(@.type=="InternalIP")]}{.address}{"\n"}{end}' 2>/dev/null \
    | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -1 || true)"
fi
[[ -n "$NODE_IP" ]] || NODE_IP="192.168.1.55"
info "NODE_IP=$NODE_IP (host bridge for PG)"

# ── Postgres: role + database ─────────────────────────────────────
info "ensuring database $AF_DB_NAME on ${PGHOST}:${PGPORT}"
if command -v psql >/dev/null 2>&1; then
  run_psql() {
    local db="$1"; shift
    if PGPASSWORD="${PGPASSWORD:-}" psql -h "$PGHOST" -p "$PGPORT" -U "$PGSUPER" -d "$db" -v ON_ERROR_STOP=1 "$@" 2>/dev/null; then
      return 0
    fi
    PGPASSWORD="${PGPASSWORD:-signals}" psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$db" -v ON_ERROR_STOP=1 "$@"
  }

  run_psql postgres -tc "SELECT 1 FROM pg_roles WHERE rolname = '$AF_DB_USER'" | grep -q 1 || \
    run_psql postgres -c "CREATE USER $AF_DB_USER WITH PASSWORD '$AF_DB_PASS'"

  run_psql postgres -tc "SELECT 1 FROM pg_database WHERE datname = '$AF_DB_NAME'" | grep -q 1 || \
    run_psql postgres -c "CREATE DATABASE $AF_DB_NAME OWNER $AF_DB_USER"

  run_psql "$AF_DB_NAME" -c "GRANT ALL ON SCHEMA public TO $AF_DB_USER" 2>/dev/null || true
  # Airflow migrations need create on public
  run_psql "$AF_DB_NAME" -c "ALTER SCHEMA public OWNER TO $AF_DB_USER" 2>/dev/null || true
  info "Postgres ready ($AF_DB_NAME / $AF_DB_USER)"
else
  info "WARN: psql not found — ensure DB $AF_DB_NAME exists manually"
fi

# ── Persistent chart secrets (fernet/jwt/api) ─────────────────────
mkdir -p "$(dirname "$SECRET_FILE")"
if [[ ! -f "$SECRET_FILE" ]]; then
  info "generating secrets → $SECRET_FILE"
  # Fernet key: url-safe base64 of 32 bytes
  FERNET="$(python3 - <<'PY'
import base64, os
print(base64.urlsafe_b64encode(os.urandom(32)).decode())
PY
)"
  API_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
  JWT_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
  cat >"$SECRET_FILE" <<EOF
# Generated by airflow_platform_bootstrap.sh — do not commit
AIRFLOW_FERNET_KEY=${FERNET}
AIRFLOW_API_SECRET_KEY=${API_KEY}
AIRFLOW_JWT_SECRET=${JWT_KEY}
EOF
  chmod 600 "$SECRET_FILE"
fi
# shellcheck source=/dev/null
set -a
# shellcheck disable=SC1090
. "$SECRET_FILE"
set +a
[[ -n "${AIRFLOW_FERNET_KEY:-}" && -n "${AIRFLOW_API_SECRET_KEY:-}" && -n "${AIRFLOW_JWT_SECRET:-}" ]] \
  || die "incomplete secrets in $SECRET_FILE"

# ── Host bridge + DAG ConfigMap + cross-ns RBAC ───────────────────
info "applying host bridge (PG proxy) for ns/$NAMESPACE"
k apply -f "$MANIFEST_DIR/host-bridge.yaml"
# Re-assert zarf ignore on namespace (mutate webhook must skip this ns)
k annotate ns "$NAMESPACE" zarf.dev/agent=ignore --overwrite 2>/dev/null || true
k label ns "$NAMESPACE" zarf.dev/agent=ignore --overwrite 2>/dev/null || true
# Drop legacy manual Endpoints if present (Service now selects proxy pods)
k -n "$NAMESPACE" delete endpoints signals-postgres --ignore-not-found 2>/dev/null || true
info "waiting for signals-postgres-proxy..."
k -n "$NAMESPACE" rollout status deploy/signals-postgres-proxy --timeout=120s

info "applying CI DAG ConfigMap (signals_ci + legacy smoke dual-map + eventing DAGs when present)"
# values-signals.yaml subPath-mounts every key below; a key missing from the CM leaves the
# dag-processor stuck in ContainerCreating. Keep this set ⊇ the mounted files.
cm_args=(
  --from-file=signals_ci_dag.py="$MANIFEST_DIR/dags/signals_ci_dag.py"
  --from-file=signals_smoke_dag.py="$MANIFEST_DIR/dags/signals_smoke_dag.py"
  # Coordination Activities: inter-project intent as runs of the coord_* DAGs,
  # declared only by the Signals engine (zndx.scheduler.v1 Declare/Renew/Release)
  # and OBSERVED by Airflow (SignalsActivitySensor → lease trigger). The
  # sensor/trigger module is mounted into /opt/airflow/plugins (triggerer import).
  --from-file=coord_activity_dag.py="$MANIFEST_DIR/dags/coord_activity_dag.py"
  --from-file=coord_signals.py="$MANIFEST_DIR/plugins/coord_signals.py"
  --from-file=coord_lease.py="$MANIFEST_DIR/plugins/coord_lease.py"
  # Workload catalogue: engines submit (Scheduler/SyncWorkloads), Signals writes
  # the zndx_workloads Variable, this module generates one DAG per workload.
  --from-file=coord_workloads_dag.py="$MANIFEST_DIR/dags/coord_workloads_dag.py"
)
EVENTING_DAGS="$ROOT/config/k8s/eventing/dags"
for f in signals_eventing_ci_dag.py signals_eventing_smoke_dag.py; do
  if [[ -f "$EVENTING_DAGS/$f" ]]; then
    cm_args+=(--from-file="$f=$EVENTING_DAGS/$f")
  fi
done
k -n "$NAMESPACE" create configmap signals-airflow-dags "${cm_args[@]}" \
  --dry-run=client -o yaml | k apply -f -

# Metaflow ns may not exist yet — apply when present
if k get ns metaflow >/dev/null 2>&1; then
  info "applying Airflow → metaflow pod-launcher RBAC"
  k apply -f "$MANIFEST_DIR/rbac-metaflow.yaml"
else
  info "WARN: ns/metaflow missing — skip rbac-metaflow (run just metaflow-platform first)"
fi

# ── Helm install / upgrade ────────────────────────────────────────
info "helm upgrade --install $RELEASE (chart $CHART_DIR)"
# postgresql chart dep is packaged as .tgz; disable via values
helm upgrade --install "$RELEASE" "$CHART_DIR" \
  --namespace "$NAMESPACE" \
  --create-namespace \
  -f "$VALUES" \
  --set-string "data.metadataConnection.user=${AF_DB_USER}" \
  --set-string "data.metadataConnection.pass=${AF_DB_PASS}" \
  --set-string "data.metadataConnection.db=${AF_DB_NAME}" \
  --set-string "data.metadataConnection.host=signals-postgres" \
  --set-string "fernetKey=${AIRFLOW_FERNET_KEY}" \
  --set-string "apiSecretKey=${AIRFLOW_API_SECRET_KEY}" \
  --set-string "jwtSecret=${AIRFLOW_JWT_SECRET}" \
  --timeout "${TIMEOUT}s" \
  --wait=false

info "waiting for core deployments (timeout ${TIMEOUT}s)..."
# Migrations + create-user are helm hooks; wait for deployments
deadline=$((SECONDS + TIMEOUT))
ready=0
while (( SECONDS < deadline )); do
  api_ready="$(k -n "$NAMESPACE" get deploy -l component=api-server -o jsonpath='{.items[0].status.readyReplicas}' 2>/dev/null || echo 0)"
  sch_ready="$(k -n "$NAMESPACE" get deploy -l component=scheduler -o jsonpath='{.items[0].status.readyReplicas}' 2>/dev/null || echo 0)"
  api_ready="${api_ready:-0}"
  sch_ready="${sch_ready:-0}"
  if [[ "$api_ready" -ge 1 && "$sch_ready" -ge 1 ]]; then
    ready=1
    break
  fi
  # surface hook job status occasionally
  if (( SECONDS % 30 < 3 )); then
    info "status: api=$api_ready scheduler=$sch_ready"
    k -n "$NAMESPACE" get pods,jobs 2>/dev/null | head -25 || true
  fi
  sleep 5
done

if [[ "$ready" -ne 1 ]]; then
  info "pod diagnostics:"
  k -n "$NAMESPACE" get pods,jobs,svc -o wide || true
  k -n "$NAMESPACE" logs -l component=scheduler --tail=40 2>/dev/null || true
  k -n "$NAMESPACE" logs -l component=api-server --tail=40 2>/dev/null || true
  # migration job
  k -n "$NAMESPACE" logs -l component=run-airflow-migrations --tail=60 2>/dev/null || true
  die "Airflow deployments not ready within ${TIMEOUT}s"
fi

# Health: API server
info "probing API at $API_URL"
ok=0
for _ in $(seq 1 40); do
  # AF3 health endpoint variants
  if curl -sf -m 3 "${API_URL}/api/v2/version" >/dev/null 2>&1 \
    || curl -sf -m 3 "${API_URL}/api/v1/version" >/dev/null 2>&1 \
    || curl -sf -m 3 "${API_URL}/health" >/dev/null 2>&1 \
    || curl -sf -m 3 "${API_URL}/api/v2/monitor/health" >/dev/null 2>&1; then
    ok=1
    break
  fi
  # unauthenticated root may still return 200/302 for UI
  code="$(curl -s -o /dev/null -w '%{http_code}' -m 3 "${API_URL}/" 2>/dev/null || echo 000)"
  if [[ "$code" =~ ^(200|302|303|401|403)$ ]]; then
    ok=1
    break
  fi
  sleep 3
done

if [[ "$ok" -ne 1 ]]; then
  k -n "$NAMESPACE" get pods,svc -o wide || true
  die "API not healthy at $API_URL"
fi

# Ensure lab admin (createUserJob hooks can race first install)
AF_ADMIN_USER="${AIRFLOW_ADMIN_USER:-admin}"
AF_ADMIN_PASS="${AIRFLOW_ADMIN_PASSWORD:-admin}"
if k -n "$NAMESPACE" get deploy airflow-api-server >/dev/null 2>&1; then
  info "ensuring admin user ${AF_ADMIN_USER}"
  k -n "$NAMESPACE" exec deploy/airflow-api-server -c api-server -- \
    airflow users create \
      --username "$AF_ADMIN_USER" --password "$AF_ADMIN_PASS" \
      --firstname Signals --lastname Admin \
      --role Admin --email admin@signals.local \
    >/dev/null 2>&1 || true
fi

info "OK — Airflow 3 platform"
info "  UI/API:  $API_URL  (admin / admin; JWT via POST /auth/token)"
info "  ns:      $NAMESPACE  release=$RELEASE"
info "  secrets: $SECRET_FILE"
info "  chart:   components/airflow/chart (3.1.7)"
info "  CI DAG:  signals_ci (ConfigMap signals-airflow-dags)"
info "  trigger: just airflow-platform-ci"
exit 0
