KuduClient {
  com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    useTicketCache=false
    doNotPrompt=true
    isInitiator=true
    refreshKrb5Config=true
    keyTab="/home/rch/local/src/wxs/signals/.devenv/kdc/impala.keytab"
    principal="impala/tinybox.dev.vista.zndx.org@DEV.VISTA.ZNDX.ORG";
};
Client {
  com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    useTicketCache=false
    doNotPrompt=true
    isInitiator=true
    refreshKrb5Config=true
    keyTab="/home/rch/local/src/wxs/signals/.devenv/kdc/impala.keytab"
    principal="impala/tinybox.dev.vista.zndx.org@DEV.VISTA.ZNDX.ORG";
};
