log4j.rootLogger=WARN, glog
log4j.appender.glog=org.apache.impala.util.GlogAppender
log4j.appender.glog.layout=org.apache.log4j.PatternLayout
log4j.appender.glog.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p [%t] %c{1} - %m%n

# Debug Hive MetaStore client
log4j.logger.org.apache.hadoop.hive.metastore=DEBUG
log4j.logger.org.apache.thrift=DEBUG
log4j.logger.org.apache.hadoop.hive.conf=DEBUG
